---
- name: Install apts - apache2
  apt:
    name: 
      - apache2
    state: present
    force_apt_get: yes

- name: Recursively change ownership of /etc/apache2/sites-available
  file:
    path: /etc/apache2/sites-available
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: Recursively change ownership of /etc/apache2/sites-enabled
  file:
    path: /etc/apache2/sites-enabled
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: Enable apache2 ssl mods
  apache2_module: 
    name: ssl
    state: present

- name: Enable apache2 rewrite mods
  apache2_module: 
    name: rewrite
    state: present

- name: Enable apache2 headers mods
  apache2_module: 
    name: headers
    state: present

- name: Enable apache2 proxy mods
  apache2_module: 
    name: proxy
    state: present

- name: Enable apache2 proxy_http mods
  apache2_module: 
    name: proxy_http
    state: present

- name: Enable apache2 proxy_balancer mods
  apache2_module: 
    name: proxy_balancer
    state: present

- name: Enable apache2 lbmethod_byrequests mods
  apache2_module: 
    name: lbmethod_byrequests
    state: present
  notify: restart apache2

- name: Copy apache2 dir.conf
  template:
    src: dir.conf.j2
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: www-data
    group: www-data
    mode: 0775

- name: Create a /var/www/webroot directory if it does not exist
  file:
    path: /var/www/webroot
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy apache2 example.conf
  template:
    src: example.conf.j2
    dest: /etc/apache2/sites-available/example.conf
    owner: ubuntu
    group: ubuntu
    mode: 0664