---
- hosts: vm
  gather_facts: False
  become: True
  
  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
        force_apt_get: yes
  
  roles:
    - { role: swapfile, swapfile_size: 1GB, swapfile_file: /swapfile, tags: [swapfile], swapfile_swappiness: 10, swapfile_vfs_cache_pressure: 50 }
    - { role: shell, user: ubuntu, zsh_theme: tjkirch }