---
- hosts: vm
  gather_facts: False
  become: True
  vars:
    domain: YOURDOMAINNAME.com
    subdomain: False
    ssl: True
    http2: True
    email: support@YOURDOMAINNAME.com

  roles:
    - { role: apache-site }