---
- hosts: vm
  gather_facts: False
  become: True
  vars:
    system_user: "ubuntu"
    ansible_distribution_release: bionic
    swapfile_size: 2GB
    php_mod: "apache2"
    mysql_password: "CHANGEME"
    domain: YOURDOMAINNAME.com
    subdomain: www.YOURDOMAINNAME.com
    ssl: True
    email: support@YOURDOMAINNAME.com

  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
        force_apt_get: yes

  roles:
    - { role: base }
    - { role: swapfile }
    - { role: shell }
    - { role: apache }
    - { role: php }
    - { role: composer }
    - { role: docker }
    - { role: mariadb }
    - { role: letsencrypt }
    - { role: nodejs, ansible_os_family: Debian }
    - { role: apache-site }
