---
- name: Add the user >>{{ system_user }}<< with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  user:
    name: "{{ system_user }}"
    shell: /bin/bash
    groups: "{{ system_user }},adm,sudo,www-data"
    append: yes
    create_home: yes
    password: "{{ user_pass }}"

- name: Add the user >>{{ system_user }}<< to sudoer file without password
  template:
    src: init-user.j2
    dest: "/etc/sudoers.d/{{ system_user }}-init-user "
    owner: "root"
    group: "root"
    mode: 0600
    force: no