---
- hosts: vm
  gather_facts: False
  become: True
  vars:
    system_user: "ubuntu"
    user_pass: "nvsZf8GrYFpGfDUmQ"
    ansible_distribution_release: bionic
    swapfile_size: 2GB
    php_mod: "apache2"
    mysql_password: "7XD4-1A0hb-zw5-SQL"
    domain: YOURDOMAINNAME.com
    subdomain: www.YOURDOMAINNAME.com
    ssl: True
    email: support@YOURDOMAINNAME.com

  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
        force_apt_get: yes
    - name: Set timezone to Asia/Taipei
      timezone:
        name: Asia/Taipei
        
  roles:
    # - { role: user }
    - { role: base }
    - { role: swapfile }
    - { role: shell }
    - { role: apache }
    # - { role: php }
    # - { role: php5 }
    - { role: php73 }
    - { role: composer }
    - { role: docker }
    # - { role: mariadb }
    # - { role: letsencrypt }
    # - { role: nodejs, ansible_os_family: Debian }
    # - { role: proxmox }
    # - { role: apache-site }
