---
- name: Install apts - apache2 & letsencrypt
  apt:
    name: 
      - apache2
      - python3-certbot-apache
    state: present
    force_apt_get: yes

- name: Recursively change ownership of /etc/apache2/sites-available
  file:
    path: /etc/apache2/sites-available
    state: directory
    recurse: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775

- name: Recursively change ownership of /etc/apache2/sites-enabled
  file:
    path: /etc/apache2/sites-enabled
    state: directory
    recurse: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775

- name: Enable apache2 ssl mods
  apache2_module: 
    name: ssl
    state: present

- name: Enable apache2 rewrite mods
  apache2_module: 
    name: rewrite
    state: present

- name: Enable apache2 headers mods
  apache2_module: 
    name: headers
    state: present

- name: Enable apache2 proxy mods
  apache2_module: 
    name: proxy
    state: present

- name: Enable apache2 proxy_http mods
  apache2_module: 
    name: proxy_http
    state: present

- name: Enable apache2 proxy_balancer mods
  apache2_module: 
    name: proxy_balancer
    state: present

- name: Enable apache2 lbmethod_byrequests mods
  apache2_module: 
    name: lbmethod_byrequests
    state: present
    
- name: Copy apache2 dir.conf
  template:
    src: dir.conf.j2
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: www-data
    group: www-data
    mode: 0664

- name: Create a /var/www/webroot directory if it does not exist
  file:
    path: /var/www/webroot
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy apache2 example.conf
  template:
    src: example.conf.j2
    dest: /etc/apache2/sites-available/example.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no
    
- name: set default folder groups of /var/www
  shell: setfacl -R -m g:www-data:rwx /var/www
    
- name: set folder permission following parent (/var/www)
  shell: chmod -R g+s /var/www

- name: Create apache2 mutex-file.conf
  template:
    src: mutex-file.conf.j2
    dest: /etc/apache2/conf-available/mutex-file.conf
    owner: root
    group: root
    mode: 0644

- name: Enable mutex config
  file:
    src: /etc/apache2/conf-available/mutex-file.conf
    dest: /etc/apache2/conf-enabled/mutex-file.conf
    owner: root
    group: root
    state: link

- name: change apache2 default user - {{system_user}}
  replace:
    path: /etc/apache2/envvars
    regexp: 'export APACHE_RUN_USER=www-data'
    replace: 'export APACHE_RUN_USER={{system_user}}'
    
- name: make default group user www-data write-able (775)
  blockinfile:
    path: /etc/apache2/envvars
    insertafter: EOF
    marker: "# umask 002 to create files with 0664 and folders with 0775"
    block: umask 002
  notify: restart apache2

- name: Create check repair service cronjob - apache2
  cron:
    name: Check & Repair apache2 service every 5 mins
    job: "/srv/scripts/check-repair-apache2.sh  > /dev/null 2>&1"
    minute: "*/5"

- name: Restart apache2 weekly for reload SSL
  cron:
    name: Restart apache2 weekly
    job: "/etc/init.d/apache2 restart > /dev/null 2 > &1"
    weekday: "6"

- name: create /etc/letsencrypt directory if they don't exist
  file:
    path: /etc/letsencrypt
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775

- name: Copy apache2 options-ssl-apache.conf
  template:
    src: options-ssl-apache.conf.j2
    dest: /etc/letsencrypt/options-ssl-apache.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no