---
# defaults file for docker
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_install_compose: true
docker_compose_version: "1.24.0"
docker_compose_path: /usr/local/bin/docker-compose
docker_apt_release_channel: stable
docker_apt_arch: amd64
ansible_distribution: ubuntu
ansible_distribution_release: bionic
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: True
docker_yum_repo_url: https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0
docker_users: ubuntu
system_user: ubuntu
mysql_password: CHANG3M3@2019