---
- hosts: vm
  gather_facts: False
  become: True
  vars:
    system_user: "ubuntu"
    system_timezone: "Asia/Taipei"
    user_pass: "nvsZf8GrYFpGfDUmQ"
    ansible_distribution_release: jammy
    swapfile_size: 2GB
    php_mod: "apache2"
    sql_pass: "A4niENMeF4bBE6hZ"
    domain: YOURDOMAINNAME.com
    subdomain: www.YOURDOMAINNAME.com
    ssl: True
    email: support@YOURDOMAINNAME.com
    php_upgrade: True
    ssh_authorized_keys_file:
      - public_keys/roy
      - public_keys/hsiang
      - public_keys/hububble-dev

  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
        force_apt_get: yes
    - name: Set timezone to Asia/Taipei
      timezone:
        name: Asia/Taipei
        
  roles:
    - { role: user }
    - { role: base }
    - { role: swapfile }
    - { role: shell }
    - { role: apache }
    # - { role: nginx }
    # - { role: php }
    # - { role: php5 }
    - { role: php74 }
    - { role: composer }
    # - { role: mariadb }
    - { role: letsencrypt }
    - { role: docker, ansible_os_family: Debian, ansible_distribution: Ubuntu, docker_compose_version: "2.20.3", ansible_distribution_version: "22.04", ansible_distribution_release: "jammy" }
    # - { role: proxmox }
    # - { role: apache-site }
