---
- name: add php repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install apts - php
  apt:
    name: 
      - php7.4
      - php7.4-cli
      - php7.4-fpm
      - php7.4-common
      - php7.4-curl
      - php7.4-dev
      - php7.4-mysql
      - php7.4-bcmath
      - php7.4-bz2
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-redis
      - php7.4-pgsql
      - php7.4-soap
      - php7.4-zip
      - php7.4-gd
      - php7.4-ldap
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-memcache
      - php7.4-memcached
      - libapache2-mod-php7.4
      - libapache2-mod-fcgid
    state: present
    force_apt_get: yes

# - name: Enable the Apache2 module proxy_fcgi, setenvif, proxy
#   when: php_mod == "fpm"
#   community.general.apache2_module:
#     state: present
#     name: "{{ item }}"
#   with_items:
#     - proxy_fcgi
#     - setenvif
#     - proxy
#   notify: 
#     - restart apache2
#     - restart fpm

- name: Enable php opcache mods
  command: phpenmod opcache

- name: Copy info.php to /var/www/html
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
    owner: www-data
    group: www-data
    mode: 0664

- name: Copy php.ini to /etc/php/7.4/{{ php_mod }}/
  template:
    src: php.ini.j2
    dest: /etc/php/7.4/{{ php_mod }}/php.ini
    owner: root
    group: root
    mode: 0664

- name: Enable apache2 php-fpm mods
  command: a2enconf php7.4-fpm
  when: php_mod == "fpm"
  notify: 
    - restart apache2
    - restart fpm

- name: Enable apache2 php 7.4 mods
  when: php_mod == "apache2"
  apache2_module: 
    name: php7.4
    state: present
  notify: 
    - restart apache2

- name: Set update default php7.4
  ansible.builtin.command: update-alternatives --set php /usr/bin/php7.4