---
- name: add php repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install apts - php
  apt:
    name: 
      - php7.4
      - php7.4-cli
      - php7.4-fpm
      - php7.4-common
      - php7.4-curl
      - php7.4-dev
      - php7.4-mysql
      - php7.4-bcmath
      - php7.4-bz2
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-redis
      - php7.4-pgsql
      - php7.4-soap
      - php7.4-zip
      - php7.4-gd
      - php7.4-ldap
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-memcache
      - php7.4-memcached
      - libapache2-mod-php7.4
    state: present
    force_apt_get: yes

- name: Disable apache2 php mods
  apache2_module: 
    name: php7.4
    state: absent
  when: php_mod == "fpm"

- name: Disable apache2 mpm_prefork mods
  command: a2dismod mpm_prefork
  when: php_mod == "fpm"

- name: Enable apache2 mpm_event mods
  command: a2enmod mpm_event
  when: php_mod == "fpm"
  notify: restart apache2

- name: Enable apache2 proxy_fcgi mods
  apache2_module: 
    name: proxy_fcgi
    state: present
  when: php_mod == "fpm"

- name: Enable apache2 setenvif mods
  apache2_module: 
    name: setenvif
    state: present
  when: php_mod == "fpm"

- name: Enable php opcache mods
  command: phpenmod opcache

- name: Copy info.php to /var/www/html
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
    owner: www-data
    group: www-data
    mode: 0664

- name: Copy php.ini to /etc/php/7.4/{{ php_mod }}/
  template:
    src: php.ini.j2
    dest: /etc/php/7.4/{{ php_mod }}/php.ini
    owner: root
    group: root
    mode: 0664

- name: Enable apache2 php-fpm mods
  command: a2enconf php7.4-fpm
  when: php_mod == "fpm"
  notify: 
    - restart apache2
    - restart php7.4-fpm

- name: Disable apache2 php 7.2 mods
  apache2_module: 
    name: php7.2
    state: absent
  when: php_upgrade == true

- name: Enable apache2 php 7.4 mods
  apache2_module: 
    name: php7.4
    state: present
  when: php_upgrade == true
  notify: 
    - restart apache2