---
- name: Create mariadb templates
  template:
    src: mariadb.j2
    dest: /srv/mariadb/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664

- name: Create Mariadb Container
  command: docker-compose -f /srv/mariadb/docker-compose.yml up -d

- name: Update motd
  lineinfile:
    path: /etc/motd
    line: "Mysql Password: {{ mysql_password }}"