---
- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
    autoclean: yes
    autoremove: yes
    force_apt_get: yes

- name: Install apts - software-properties-common,zip,unzip,mysql-client
  apt:
    name: 
      - zip
      - software-properties-common
      - unzip
      - mysql-client
      - acl
    state: present
    force_apt_get: yes

- name: Setting timezone
  timezone:
    name: "{{ system_timezone }}"

- name: create .ssh directory if they don't exist
  file:
    path: /home/{{ system_user }}/.ssh
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0700

- name: Set up multiple authorized keys
  ansible.posix.authorized_key:
    user: "{{ system_user }}"
    state: present
    key: '{{ item }}'
  with_file: "{{ ssh_authorized_keys_file }}"

- name: Create /srv/logs directory
  file:
    path: /srv/logs
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775

- name: Create /srv/scripts directory
  file:
    path: /srv/scripts
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    
- name: Create check repair services scripts
  template:
    src: "{{ item }}.j2"
    dest: "/srv/scripts/{{ item }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
  with_items:
    - check-repair-apache2.sh
    - check-repair-docker.sh
    - check-repair-mysql.sh
    - check-repair-nginx.sh
    - check-repair-supervisor.sh
    - schedule-reload-apache2.sh

- name: Recursively change ownership of /srv
  file:
    path: /srv
    state: directory
    recurse: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    
- name: append {{ system_user }} to www-data group.
  user:
    name: "{{ system_user }}"
    groups: www-data
    append: true

- name: Recursively change ownership of /var/www
  file:
    path: /var/www
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: 2775

- name: Create Motd file
  file:
    path: /etc/motd
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Add user to sudoer
  template:
    src: init-user.j2
    dest: /etc/sudoers.d/{{ system_user }}-init-user
    owner: "root"
    group: "root"
    mode: 0660