---
- name: create some directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
  with_items:
    - /srv/redis
    - /srv/memcached
    - /srv/mariadb
    - /srv/mariadb/data
    - /srv/mariadb/scripts
    - /srv/drone/
    - /srv/drone/data

- name: Create mariadb templates
  template:
    src: mariadb.j2
    dest: /srv/mariadb/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mariadb readme
  template:
    src: mariadb-readme.j2
    dest: /srv/mariadb/readme.md
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mariadb backup scripts - hourly
  template:
    src: mariadb-hourly.j2
    dest: /srv/mariadb/scripts/hourly.sh
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    force: no

- name: Create mariadb backup scripts - daily
  template:
    src: mariadb-daily.j2
    dest: /srv/mariadb/scripts/daily.sh
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    force: no

- name: Create mariadb backup scripts - monthly
  template:
    src: mariadb-monthly.j2
    dest: /srv/mariadb/scripts/monthly.sh
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    force: no

- name: Create memcached templates
  template:
    src: memcached.j2
    dest: /srv/memcached/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create redis templates
  template:
    src: redis.j2
    dest: /srv/redis/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no
    
- name: Create drone templates
  template:
    src: drone.j2
    dest: /srv/drone/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone env
  template:
    src: drone.env.j2
    dest: /srv/drone/.env
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone cicd templates(laravel)
  template:
    src: drone.yml.j2
    dest: /srv/drone/laravel.drone.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no