---
- name: create some directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
  with_items:
    - /srv/redis
    - /srv/memcached
    - /srv/mariadb
    - /srv/mariadb/data
    - /srv/mariadb/logs
    - /srv/mariadb/scripts
    - /srv/drone
    - /srv/drone/data
    - /srv/mongodb
    - /srv/mongodb/data
    - /srv/postgresql
    - /srv/postgresql/data

- name: Create mariadb templates
  template:
    src: mariadb.j2
    dest: /srv/mariadb/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mariadb readme
  template:
    src: mariadb-readme.j2
    dest: /srv/mariadb/readme.md
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mariadb backup scripts
  template:
    src: "mariadb-{{ item }}.j2"
    dest: "/srv/mariadb/scripts/{{ item }}.sh"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    force: no
  with_items:
    - hourly
    - daily
    - all-daily
    - monthly

- name: Create memcached templates
  template:
    src: memcached.j2
    dest: /srv/memcached/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create redis templates
  template:
    src: redis.j2
    dest: /srv/redis/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no
    
- name: Create drone github templates
  template:
    src: drone-github.j2
    dest: /srv/drone/github-docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone bitbucket templates
  template:
    src: drone-bitbucket.j2
    dest: /srv/drone/bitbucket-docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone env
  template:
    src: drone.env.j2
    dest: /srv/drone/.env
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone cicd templates(laravel)
  template:
    src: drone.yml.j2
    dest: /srv/drone/laravel.drone.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mongodb templates
  template:
    src: mongodb.j2
    dest: /srv/mongodb/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create postgresql templates
  template:
    src: postgresql.j2
    dest: /srv/postgresql/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no