---
- name: create some directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
  with_items:
    - /srv/redis
    - /srv/memcached
    - /srv/mariadb
    - /srv/mariadb/data
    - /srv/mariadb/logs
    - /srv/mariadb/scripts
    - /srv/drone
    - /srv/drone/data
    - /srv/mongodb
    - /srv/mongodb/data
    - /srv/postgresql
    - /srv/postgresql/data
    - /srv/php
    - /srv/php/config
    - /srv/php/webroot

- name: Create mariadb templates
  template:
    src: mariadb.j2
    dest: /srv/mariadb/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mariadb readme
  template:
    src: mariadb-readme.j2
    dest: /srv/mariadb/readme.md
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mariadb backup scripts
  template:
    src: "mariadb-{{ item }}.j2"
    dest: "/srv/mariadb/scripts/{{ item }}.sh"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0775
    force: no
  with_items:
    - hourly
    - daily
    - all-daily
    - monthly

- name: Create memcached templates
  template:
    src: memcached.j2
    dest: /srv/memcached/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create redis templates
  template:
    src: redis.j2
    dest: /srv/redis/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no
    
- name: Create drone github templates
  template:
    src: drone-github.j2
    dest: /srv/drone/github-docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone bitbucket templates
  template:
    src: drone-bitbucket.j2
    dest: /srv/drone/bitbucket-docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone env
  template:
    src: drone.env.j2
    dest: /srv/drone/.env
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create drone cicd templates(laravel)
  template:
    src: drone.yml.j2
    dest: /srv/drone/laravel.drone.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create mongodb templates
  template:
    src: mongodb.j2
    dest: /srv/mongodb/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Create postgresql templates
  template:
    src: postgresql.j2
    dest: /srv/postgresql/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create php templates
  template:
    src: php.j2
    dest: /srv/php/docker-compose.yml
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create 000-default.conf
  template:
    src: php-000-default.conf.j2
    dest: /srv/php/config/000-default.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create custom.ini
  template:
    src: php-custom.ini.j2
    dest: /srv/php/config/custom.ini
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create default-ssl.conf
  template:
    src: php-default-ssl.conf.j2
    dest: /srv/php/config/default-ssl.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create htaccess-wordpress
  template:
    src: php-htaccess-wordpress.j2
    dest: /srv/php/config/htaccess-wordpress
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create proxy-apache-example.conf
  template:
    src: php-proxy-apache-example.conf.j2
    dest: /srv/php/config/proxy-apache-example.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create proxy-nginx-example.conf
  template:
    src: php-proxy-nginx-example.conf.j2
    dest: /srv/php/config/proxy-nginx-example.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: (PHP)Create wp-config.php
  template:
    src: php-wp-config.php.j2
    dest: /srv/php/config/wp-config.php
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no