---
- name: Install apts - php
  apt:
    name: 
      - php
      - php-cli
      - php-fpm
      - php-common
      - php-curl
      - php-dev
      - php-mysql
      - php-bcmath
      - php-bz2
      - php-intl
      - php-mbstring
      - php-redis
      - php-pgsql
      - php-soap
      - php-zip
      - php-gd
      - php-ldap
      - php-xml
      - php-xmlrpc
      - php-memcache
      - php-memcached
      - libapache2-mod-php
    state: present
    force_apt_get: yes

- name: Enable php opcache mods
  command: phpenmod opcache

- name: Copy info.php to /var/www/html
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
    owner: www-data
    group: www-data
    mode: 0664

- name: Copy php.ini to /etc/php/7.0/apache2/
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/apache2/php.ini
    owner: root
    group: root
    mode: 0664
  notify: 
    - restart apache2