---
- name: Install apts - php
  apt:
    name: 
      - php
      - php-cli
      - php-fpm
      - php-common
      - php-curl
      - php-dev
      - php-mysql
      - php-bcmath
      - php-bz2
      - php-intl
      - php-mbstring
      - php-redis
      - php-pgsql
      - php-soap
      - php-zip
      - php-gd
      - php-ldap
      - php-xml
      - php-xmlrpc
      - php-memcache
      - php-memcached
      - libapache2-mod-php
    state: present
    force_apt_get: yes

- name: Disable apache2 php mods
  apache2_module: 
    name: php7.0
    state: absent

- name: Disable apache2 mpm_prefork mods
  command: a2dismod mpm_prefork

- name: Enable apache2 mpm_event mods
  command: a2enmod mpm_event
  notify: restart apache2

- name: Enable apache2 proxy_fcgi mods
  apache2_module: 
    name: proxy_fcgi
    state: present

- name: Enable apache2 setenvif mods
  apache2_module: 
    name: setenvif
    state: present

- name: Enable php opcache mods
  command: phpenmod opcache

- name: Copy info.php to /var/www/html
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
    owner: www-data
    group: www-data
    mode: 0664

- name: Copy php.ini to /etc/php/7.0/fpm/
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/fpm/php.ini
    owner: root
    group: root
    mode: 0664

- name: Enable apache2 php-fpm mods
  command: a2enconf php7.0-fpm
  notify: 
    - restart apache2
    - restart php7.0-fpm