---
- name: add certbot repo
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install apts - Certbot Apache
  apt:
    name: python-certbot-apache
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Copy apache2 options-ssl-apache.conf
  template:
    src: options-ssl-apache.conf.j2
    dest: /etc/letsencrypt/options-ssl-apache.conf
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0664
    force: no

- name: Update message of the day
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Recursively change ownership of /etc/letsencrypt
  file:
    path: /etc/letsencrypt
    state: directory
    recurse: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"

- name: Create check repair service cronjob - apache-ssl
  cron:
    name: Schedule reload apache2 on Sunday for Let's encrypt SSL update
    job: "/srv/scripts/schedule-reload-apache2.sh > /dev/null 2>&1"
    weekday: "0"
    minute: "0"
    hour: "0"