---
- name: Add users public key to authorized
  template:
    src: authorized_keys.j2
    dest: /home/{{ system_user }}/.ssh/authorized_keys
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0600
    
- name: Set timezone to Asia/Taipei
  timezone:
    name: Asia/Taipei

- name: Install apts - software-properties-common,zip,unzip,mysql-client
  apt:
    name: 
      - zip
      - software-properties-common
      - unzip
      - mysql-client
    state: present
    force_apt_get: yes

- name: append {{ system_user }} to www-data group.
  user:
    name: "{{ system_user }}"
    groups: www-data
    append: true

- name: Recursively change ownership of /var/www
  file:
    path: /var/www
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: 0775
