---
- name: add certbot repo
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install apts - Certbot Apache
  apt:
    name: python-certbot-apache
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Copy apache2 options-ssl-apache.conf
  template:
    src: options-ssl-apache.conf.j2
    dest: /etc/letsencrypt/options-ssl-apache.conf
    owner: ubuntu
    group: ubuntu
    mode: 0664